baseURL = "https://srikanthmnb.github.io/"
locale = 'en-us'
title = 'Srikanth Nayak, Ph. D.'
theme = "PaperMod"

[[menu.main]]	
    name = "About"
    url = "/about/"
    weight = 30

[[menu.main]]	
    name = "Skills"
    url = "/skills/"
    weight = 30

[[menu.main]]	
    name = "Publications"
    url = "/publications/"
    weight = 40

[[menu.main]]
    name = "Research"
    url = "/gallery/"
    weight = 35

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # This allows Hugo to render standard HTML <img> tags

[params]
    homeInfoParams = false
    socialIcons = [
        { name = "googlescholar", url = "https://scholar.google.com/citations?user=j23VOUwAAAAJ&hl=en&oi=ao" },
        { name = "github", url = "https://github.com/srikanthmnb/" },
	{ name = "linkedin", url = "https://www.linkedin.com/in/nayaksrikanth/"}
    ]

    [params.profileMode]
        enabled = true
        title = "Srikanth Nayak, Ph.D."
        subtitle = "Separation Science | Colloidal & Interfacial Phenomena | Functional Nanomaterials"
        imageUrl = "headshot.jpg" # Looks directly inside your static folder
        imageWidth = 150         # Adjust size in pixels as needed
        imageHeight = 150
	imageTitle = "Srikanth Nayak"

    [params.assets]
        favicon = "/images/favicon.ico"
        favicon16x16 = "/images/favicon-16x16.png"
        favicon32x32 = "/images/favicon-32x32.png"
     #  apple_touch_icon = "/images/apple-touch-icon.png"
	
[[params.profileMode.buttons]]
  name = "Email"
  url = "mailto:srikanthmnb@gmail.com"

